### ISSUE TITLE
[Feature Request] Tmuxifier support

### ISSUE THREAD

**Issue by yiping-huang** [noctuid/tdrop#38] opened 2018-02-24 12:56 UTC
Hi, support for tmuxifier would be great!

I am now using
```
tdrop -a -f "-e tmuxifier load-session Drop-Down" alacritty
```
as alternative.

But the dropdown window would shrink to 80x24 the first time executing it.

**Comment by noctuid** [comment] 2018-02-27 02:00
`-s` now supports tmuxifier. I can't get tmuxifier to work at all with alacritty, and I cannot replicate this issue with other terminals. Does this only happen to you for alacritty or does the window also shrink for other terminals? What window manager are you using?

**Comment by yiping-huang** [comment] 2018-03-06 15:49
Archlinux, openbox, compton.

Drop-Down.session.sh
```
if initialize_session "Drop-Down"; then
  load_window "Drop-Down"
fi

finalize_and_go_to_session
```

Drop-Down.window.sh
```
new_window "Drop-Down"
split_h 50
select_pane 2
run_cmd "neofetch" 1
```

```
tdrop -a -h 37% -y 0 -f "-e tmuxifier load-session Drop-Down" alacritty
```
This works, except the initial size problem.

```
tdrop -a -h 37% -y 0 -s Drop-Down alacritty
```
This does open a drop-down terminal, but. And the initial size problem also occurs.

**Comment by noctuid** [comment] 2018-03-06 23:34
I can now replicate this issue with alacritty, but it has nothing to do with tdrop or tmuxifier. According to alacritty's help text, this is the expected behavior. Tdrop correctly/visibly resizes the window before alacritty shrinks it to 80x24. To prevent this, you should use alacritty's `-d` flag (e.g. `tdrop... -f '-d 0 0'`) to prevent alacritty from resizing the window.

> This does open a drop-down terminal, but it doesn't load the window preset.

That exact command loads the window preset correctly for me. Are you using the latest tdrop version?

**Comment by yiping-huang** [comment] 2018-03-07 00:04
Yes I am using the latest tdrop.
And I have found the culprit. It's the `TMUXIFIER_LAYOUT_PATH` enviroment variable.

**Comment by noctuid** [comment] 2018-03-08 22:15
> And I have found the culprit. It's the TMUXIFIER_LAYOUT_PATH enviroment variable.

To confirm, the issue is that it was set differently when using tdrop vs. not using tdrop as opposed to a problem with tdrop itself? I'm closing this, but if I misunderstood, I will reopen it.

> By the way. The -d trick eliminates the sizing problem. (I set the dimension 0*0 in alacritty.yml.)

This is no longer necessary as tdrop will automatically add the `-d 0 0` when using alacritty for now. See the linked issue for the reason why alacritty currently behaves like this.

**Closed by noctuid** 2018-03-08 22:15 UTC
Labels: enhancement

**Comment by yiping-huang** [comment] 2018-03-28 07:54
I got this if `TMUXIFIER_LAYOUT_PATH` is set.
![untitled](https://user-images.githubusercontent.com/28267464/38016030-55b08d46-32a0-11e8-9e3f-6bbafd661dfc.png)
